"""books

Revision ID: 18ecb660e0dc
Revises: 218796f15bde
Create Date: 2019-11-22 00:23:22.633000

"""

# revision identifiers, used by Alembic.
revision = '18ecb660e0dc'
down_revision = '218796f15bde'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
