"""books

Revision ID: 218796f15bde
Revises: e31384393bdc
Create Date: 2019-11-22 00:22:00.907000

"""

# revision identifiers, used by Alembic.
revision = '218796f15bde'
down_revision = 'e31384393bdc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
