"""books

Revision ID: 357dd1894703
Revises: 38c4e85512a9
Create Date: 2019-11-21 18:29:59.196000

"""

# revision identifiers, used by Alembic.
revision = '357dd1894703'
down_revision = '38c4e85512a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(length=30), nullable=False),
    sa.Column('strony', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
