"""books

Revision ID: e31384393bdc
Revises: 357dd1894703
Create Date: 2019-11-22 00:14:08.429000

"""

# revision identifiers, used by Alembic.
revision = 'e31384393bdc'
down_revision = '357dd1894703'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(length=64), nullable=False),
    sa.Column('opis', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('borows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(length=64), nullable=False),
    sa.Column('data', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graphics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(length=64), nullable=False),
    sa.Column('akcje', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('graphics')
    op.drop_table('events')
    op.drop_table('borows')
    op.drop_table('announcements')
    # ### end Alembic commands ###
